const {getInstructor,editBiography,addInstructorInfo,setContractState} = require("../controllers/instructorController")
const {editPassword,editEmail} = require('../controllers/userController')
const {createCourse,viewMyCourses,filterOnSubject,viewMySubjects,addLesson,addSubVid,addPreviewLink,addExcercise,addQuestion,addPromotion} = require("../controllers/courseController")
const {addComplaint} = require('../controllers/complaintController')
const express = require("express")
const {requireInstructor,requireCourseAuthor} = require('../middleware/requireAuth')


const router = express.Router()
//router.use(requireInstructor)

router.post("/createCourse",requireInstructor,createCourse)
router.get("/getInstructor",getInstructor)
router.get("/viewMyCourses",requireInstructor,viewMyCourses)
router.get("/viewMySubjects",requireInstructor,viewMySubjects)
router.get("/filterOnSubject",requireInstructor,filterOnSubject)

router.patch('/setContractState',requireInstructor,setContractState)
router.patch('/addInstructorInfo',requireInstructor,addInstructorInfo)
router.patch('/addLesson',requireCourseAuthor,addLesson)
router.patch('/addSubtitleVideoLink',requireCourseAuthor,addSubVid)
router.patch('/addPreviewLink',requireCourseAuthor,addPreviewLink)
router.patch('/addExcercise',requireCourseAuthor,addExcercise)
router.patch('/addQuestion',requireCourseAuthor,addQuestion)
router.patch('/editEmail',requireInstructor,editEmail)
router.patch('/editBiography',requireInstructor,editBiography)
router.patch('/addPromotion',requireCourseAuthor,addPromotion)
router.patch('/editPassword',requireInstructor,editPassword)
router.post('/addComplaint',requireInstructor,addComplaint)
module.exports = router