const { getInstructor, editBiography, addInstructorInfo, setContractState } = require("../controllers/instructorController")
const { editPassword, editEmail } = require('../controllers/userController')
const { createCourse, viewMyCourses, filterOnSubject, viewMySubjects, addLesson, addSubVid, addPreviewLink, addExcercise, addQuestion, addPromotion, addSubtitleToCourse, loadSubtitle } = require("../controllers/courseController")
const { addComplaint } = require('../controllers/complaintController')
const express = require("express")
const router = express.Router()


router.post("/createCourse/:id", createCourse)
router.get("/getInstructor/:id", getInstructor)
router.get("/viewMyCourses/:id", viewMyCourses)
router.get("/viewMySubjects/:id", viewMySubjects)
router.get("/filterOnSubject/:id", filterOnSubject)
router.post("/loadSubtitle/:id", loadSubtitle)

router.patch('/setContractState/:id', setContractState)
router.patch('/addSubtitleToCourse/:id', addSubtitleToCourse)
router.patch('/addInstructorInfo/:id', addInstructorInfo)
router.patch('/addLesson/:id', addLesson)
router.patch('/addSubtitleVideoLink/:id', addSubVid)
router.patch('/addPreviewLink/:id', addPreviewLink)
router.patch('/addExcercise/:id', addExcercise)
router.patch('/addQuestion/:id', addQuestion)
router.patch('/editEmail/:id', editEmail)
router.patch('/editBiography/:id', editBiography)
router.patch('/addPromotion/:id', addPromotion)
router.patch('/editPassword/:id', editPassword)
router.post('/addComplaint/:id', addComplaint)
module.exports = router